# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 150)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 47, 13))
        self.label_3.setObjectName("label_3")
        self.Reverse = QtWidgets.QRadioButton(self.centralwidget)
        self.Reverse.setGeometry(QtCore.QRect(260, 70, 82, 17))
        self.Reverse.setObjectName("Reverse")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label.setObjectName("label")
        self.FieldEnter = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.FieldEnter.setGeometry(QtCore.QRect(60, 70, 91, 31))
        self.FieldEnter.setObjectName("FieldEnter")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 31, 21))
        self.label_2.setObjectName("label_2")
        self.Expression = QtWidgets.QRadioButton(self.centralwidget)
        self.Expression.setGeometry(QtCore.QRect(260, 40, 82, 17))
        self.Expression.setObjectName("Expression")
        self.TextEnter = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.TextEnter.setGeometry(QtCore.QRect(10, 30, 231, 31))
        self.TextEnter.setObjectName("TextEnter")
        self.Button = QtWidgets.QPushButton(self.centralwidget)
        self.Button.setGeometry(QtCore.QRect(160, 70, 81, 31))
        self.Button.setObjectName("Button")
        self.TextOut = QtWidgets.QTextEdit(self.centralwidget)
        self.TextOut.setGeometry(QtCore.QRect(60, 110, 271, 31))
        self.TextOut.setObjectName("TextOut")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Ответ:"))
        self.Reverse.setText(_translate("MainWindow", "Обратное"))
        self.label.setText(_translate("MainWindow", "Выражение:"))
        self.label_2.setText(_translate("MainWindow", "Поле:"))
        self.Expression.setText(_translate("MainWindow", "Выражение"))
        self.Button.setText(_translate("MainWindow", "Вычислить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
